services:
  my-rabbitmq:
    image: rabbitmq:3.13.4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker-conf/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker-conf/rabbitmq/log:/var/log/rabbitmq
    networks:
      - minha-rede-rabbitmq
networks:
  minha-rede-rabbitmq:
    driver: bridge
  